version: '3.8'

services:
  telegram-bot:
    container_name: telegram-bot
    build:
      context: .
      target: production
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - bot-network

  postgres:
    container_name: telegram-bot-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres_data: 